# site settings
title: MySite
subtitle: made using massively
email: realanupreet@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "jekyllstart" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# social settings
500px_url:
facebook_url:
github_url: https://github.com/realanupreet
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/real.anupreet/
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
